version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres-sweater
    ports:
      - 5434:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: sweater
      POSTGRES_USER: sweater
      POSTGRES_PASSWORD: sweater